#!/bin/sh

clear;
echo 'Running Alpine Labs Spark Loader. Last Updated Jun 26 2017 by SAH' ;
echo 'Listening for Data Pin(s) to go from low to high, indicating a DUT is ready' ;
echo '' ;

import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)

GPIO.setup(18, GPIO.IN, pull_up_down=GPIO.PUD_UP)

while True:
    input_state = GPIO.input(18)
    if input_state == False:
        print('Button Pressed')
        time.sleep(0.2)
		fi
done

while true;

	python /home/pi/alpine_utilities/pulse-LED.py 0.1 &
	sleep 0.1;

	do if ( lsusb | grep Freescale >/dev/null ) || ( lsusb | grep a531:0000 >/dev/null ); then
		echo 'found a device, going to sleep for a bit'
		sleep 10;

		python /home/pi/alpine_utilities/pulse-LED.py 15 &

		# Check to see if the device was mounted correctly
		if ls /media/pi/ | grep Pulse >/dev/null; then
			echo 'Pulse was mounted correctly'
		else
			echo 'Mounting Pulse...'
			sudo mkdir /media/pi/Pulse >/dev/null;
			sudo mount -t vfat /dev/sd* /media/pi/Pulse >/dev/null;
		fi;

		echo 'Copying Firmware to Pulse. Please Wait...';
		cp /home/pi/alpine_utilities/pulse-firmware.sb /media/pi/Pulse/ >/dev/null;

		sleep 15;
		echo 'Done Copying. You may now remove Pulse.';

		# Wait for the Operator to unplug the device
		while lsusb | grep Freescale >/dev/null;
			do echo 'Please remove Pulse to continue.';
			sleep 1;
		done;


		clear;
		echo 'Running Alpine Labs Spark Loader. Last Updated Jun 26 2017 by SAH' ;
		echo 'Listening for Data Pin(s) to go from low to high, indicating a DUT is ready' ;
		echo '' ;
	fi;

done
